version: "3"
services:
  app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
        - 3003:3000
    volumes:
        - .:/app
        - /app/node_modules
